pip install pystyle
pip install os
pip install sys
pip install webbrowser
pip install time
pip install ctypes
pip install discord
pip install discord.ext
pip install asyncio
pip install logging
pip install random
pip install colorama
pip install requests
pip install json
pip install datetime
pip install random
pip install string
pip install sleep
pip install commands
pip install Fore
pip install queue
pip install pandas
pip install system
pip install colored
pip install sleep
pip install Back
pip install Style
pip install init
pip install fg
pip install attr
pip install options
pip install requests.api
pip install os.path
pip install flask
pip install threading
pip install urllib.request
pip install six
pip install lxml
pip install threading
pip install importlib.resources
pip install base64
pip install genericpath
pip install traceback
pip install urllib.request
pip install urllib.parse
pip install asyncio
pip install classes
pip install asyncio
python DesmondTool.py

